### ISSUE TITLE
Lots of  java.util.concurrent.CancellationException if I select Project -> Clean

### ISSUE THREAD

**Issue by vogella** [angelozerr/jdt-codemining#83]
I triggere can clean build for my Workspace and receive lots of exceptions, see below.

!ENTRY org.eclipse.jface.text 4 0 2018-11-02 15:05:00.607
!MESSAGE java.util.concurrent.CancellationException
!STACK 0
java.util.concurrent.CompletionException: java.util.concurrent.CancellationException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.util.concurrent.CancellationException
	at org.eclipse.jface.internal.text.codemining.CancellationExceptionMonitor.isCanceled(CancellationExceptionMonitor.java:33)
	at org.eclipse.jdt.experimental.ui.javaeditor.codemining.JavaASTCodeMiningProvider.lambda$0(JavaASTCodeMiningProvider.java:65)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	... 5 more

!ENTRY org.eclipse.jface.text 4 0 2018-11-02 15:05:00.623
!MESSAGE java.util.concurrent.CancellationException
!STACK 0
java.util.concurrent.CompletionException: java.util.concurrent.CancellationException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.util.concurrent.CancellationException
	at org.eclipse.jface.internal.text.codemining.CancellationExceptionMonitor.isCanceled(CancellationExceptionMonitor.java:33)
	at org.eclipse.debug.ui.codemining.provisional.AbstractDebugVariableCodeMiningProvider.lambda$0(AbstractDebugVariableCodeMiningProvider.java:56)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	... 5 more

**Comment by angelozerr** [comment]
I think this log comes from https://bugs.eclipse.org/bugs/show_bug.cgi?id=539317

I think we should keep logs but filter CancellationExceptionMonitor, please create a bug and add the author of https://bugs.eclipse.org/bugs/show_bug.cgi?id=539317 in order we have a discussion

**Comment by angelozerr** [comment]
@vogella it's a Platform bug, I hav ecreated the issue at https://bugs.eclipse.org/bugs/show_bug.cgi?id=540779

**Comment by vogella** [comment]
Thanks Angelo, closing as this is worked on in Platform
