### ISSUE TITLE
NPE in logs

### ISSUE THREAD

**Issue by fipro78** [angelozerr/jdt-codemining#9]
I tried to test your plugin today with Photon M6 and it did not work at all. Not sure what the cause is, but I have found the following exception in the workspace logs:

java.lang.NullPointerException
	at org.eclipse.jdt.junit.codemining.JUnitCodeMiningProvider$CodeMiningTestRunListener.sessionFinished(JUnitCodeMiningProvider.java:59)
	at org.eclipse.jdt.internal.junit.model.TestRunListenerAdapter.fireSessionFinished(TestRunListenerAdapter.java:45)
	at org.eclipse.jdt.internal.junit.model.TestRunListenerAdapter.sessionEnded(TestRunListenerAdapter.java:69)
	at org.eclipse.jdt.internal.junit.model.TestRunSession$TestSessionNotifier.testRunEnded(TestRunSession.java:656)
	at org.eclipse.jdt.internal.junit.model.RemoteTestRunnerClient$3.run(RemoteTestRunnerClient.java:516)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.jdt.internal.junit.model.RemoteTestRunnerClient.testRunEnded(RemoteTestRunnerClient.java:513)
	at org.eclipse.jdt.internal.junit.model.RemoteTestRunnerClient.access$9(RemoteTestRunnerClient.java:508)
	at org.eclipse.jdt.internal.junit.model.RemoteTestRunnerClient$DefaultProcessingState.readMessage(RemoteTestRunnerClient.java:106)
	at org.eclipse.jdt.internal.junit.model.RemoteTestRunnerClient.receiveMessage(RemoteTestRunnerClient.java:381)
	at org.eclipse.jdt.internal.junit.model.RemoteTestRunnerClient.access$27(RemoteTestRunnerClient.java:380)
	at org.eclipse.jdt.internal.junit.model.RemoteTestRunnerClient$ServerConnection.run(RemoteTestRunnerClient.java:278)

Maybe it helps you in fixing some issues.

**Comment by angelozerr** [comment]
I close this issue which fixes the NPE.
